version: "3.9"

services:
  # MongoDB Service
  mongodb_service:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27018:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: >
        mongosh --quiet --eval "
        try {
          rs.status()
        } catch (err) {
          rs.initiate({
            _id: 'rs0',
            members: [{ _id: 0, host: 'mongodb_service:27017' }]
          })
        }"
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - mongodb_service_data:/data/db
      - mongodb_service_config:/data/configdb
    networks:
      - shared_network

  # Redis Service
  redis_service:
    image: redis:alpine
    ports:
      - "6380:6379" 
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - shared_network

  # Move+ backend
  move+_backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env.dev
    volumes:
      - .:/app               
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - shared_network

volumes:
  mongodb_service_data:
  mongodb_service_config:

networks:
  shared_network:
    name: shared_network
